version: '3'
services:

  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: lumen-apss
    container_name: app
    restart: unlees-stopped
    tty: true
    environment:
      SERVICE_NAME: app
      SERVICE_TAGS: dev
    working_dir: /var/www
    depends_on:
      - webserver
    networks:
      - lumen-app

  webserver:
    image: nginx:alpine
    container_name: webserver
    restart: unless-stopped
    tty: true
    ports:
      - "8089:80"
      - "443:443"
    networks:
      - lumen-app

networks:
  lumen-app:
    driver: bridge